few small fixes

diff --git a/adduser b/adduser
--- a/adduser
+++ b/adduser
@@ -50,7 +50,7 @@ if [ $(id -u) -eq 0 ]; then
 		tput cup $((centerrow+7)) $centercol
 		echo "========================================="
 		tput cup $((centerrow+9)) $centercol
-		echo -e "\t     \e[91mUser '$username' exists!\e[0m"
+		echo -e "\t   \e[91mUser '$username' exists!\e[0m"
 		sleep 2
 		clear
 		exit 1
@@ -61,7 +61,7 @@ if [ $(id -u) -eq 0 ]; then
 		tput cup $((centerrow+7)) $centercol
 		echo "=========================================" 
 		tput cup $((centerrow+9)) $centercol
-		[ $? -eq 0 ] && echo -e " \t  \e[92mUser has been added to system!\e[0m" || echo -e "\t\t\e[91mFailed to add a user!\e[0m"
+		[ $? -eq 0 ] && echo -e "    \e[92mUser has been added to system!\e[0m" || echo -e "\t    \e[91mFailed to add a user!\e[0m"
 		sleep 2	
 	fi
 
